General:
  dataset: "UniGeo" # [UniGeo, PGPS9K, MATH-Geometry, GeometryQA, Geometry3K, GeoQA+]
  model_type: "opensource_model" # [api_model, opensource_model]
  model_name: "llama-2-7b"
  eval_dataset_path: "LLM_eval/"    # relative directory path
  input_file: "dataset_merge/all.json" # only file name
  output_dir: "result" # relative dir path 
  weight_path: "/users/gvb20207/Code_weights/llama-2-7b-chat-hf"   # absolute path for server running
  # cached_file: "/Users/knight/Code/1_PHD_CODE/GeoEval/Cached/UniGeo_bert-base-uncased"  # absolute path, the processed cache file for "input_file", if False will created later
  cached_file: False
  cached_dir: "Cached/"
  max_seq_length: 1024
  bsz: 1
  load_in_8bit: False
  from_local: True
  merge_type: "naive"
  prompt_type: "llama2"
  sample_number: 10  # set -1 to use all data