General:
  dataset: "GeoEval" # 随便取
  model_type: "api_model" 
  model_name: "wizardmath" 
  eval_dataset_path: "LLM_eval/"    
  input_file: "dataset_merge/select.json" 
  output_dir: "result/{model_name}" 
  max_seq_length: 2048 
  bsz: 1  
  weight_path: ""             
  merge_type: "naive"   
  sample_number: 10     